server:
  port: 8081

spring:
  application:
    name: justbutton
  datasource:
    url: jdbc:mysql://mysql:3306/justbutton?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: hlee
    password: Dlgywls910129!
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    
logging:
  level:
    com.justbutton: DEBUG
    org.springframework.web: DEBUG
  file:
    name: /app/logs/justbutton.log
    