server:
  port: 8080

spring:
  application:
    name: justbutton
  datasource:
    url: jdbc:mysql://localhost:3306/justbutton
    username: root
    password: Dlgywls910129!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true